# Site Settings
title:               README
tagline:             freddie's Blog
description:
baseurl:            "/blog"
url:                #"https://freddiekim.github.io"
github:
  url:               #"https://freddiekim.github.io/Blog_Lagrange"
author:
  name:              "freddie kim"
  email:             "freddiekim.sr@gmail.com"
  twitter:           ""
  instagram:         ""
  github:            "freddiekim"
  facebook:          ""
  linkedin:          ""
navigation:
- title: Blogs
  url: /Blogs
- title: Archives
  url: /Archives
- title: Diary
  url: /Diary
- title: Links(others)
  url: /Links(others)
- title: Search
  url: /Search
- title: AboutMe
  url: /AboutMe

paginate:            5
disqus:              #"your-disqus"

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
gems:                [jekyll-paginate]
