# Site Settings
title:               README
tagline:             freddie's Blog
description:
baseurl:            "/blog"
url:                #"https://freddiekim.github.io"
github:
  url:               #"https://freddiekim.github.io/Blog_Lagrange"
author:
  name:              "freddie kim"
  email:             "freddiekim.sr@gmail.com"
  twitter:           ""
  instagram:         ""
  github:            "freddiekim"
  facebook:          ""
  linkedin:          ""
navigation:
- title: Archives
  url: /Archives
- title: Book&Papers
  url: /BooksnPapers
- title: Diary
  url: /Diary
- title: Stock
  url: /Stock
- title: Links
  url: /Links
- title: AboutMe
  url: /AboutMe

paginate:            6
disqus:              "freddiekim" #"https://freddiekim.disqus.com"  #"your-disqus"

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
gems:                [jekyll-paginate]
